### PR TITLE
Ancestral sample

### PR DESCRIPTION
**Pull request by DL42**
First prototype of tracking mutations from a simulation. Fixes EdgesetTable > EdgeTable in prototype.

### CODE REVIEW

**Comment by DL42** [comment]
1. I kept changes to prototype which fixed EdgesetTable > EdgeTable. Other than that I discarded all the mutation tracking and created a new file prototype_with_mutations.py. 

2. I originally left the additional mutation generation through msprime to represent "neutral" mutations as opposed "selected" mutations from the simulation. However, since I'm just testing toy examples right now, I agree, I've eliminated mutation generation via msprime in prototype_with_mutations.py. Msprime simplifies mutation and site tables generated during the simulation. 

However, I'm not sure how to test if the simplification is done correctly ... I can test that the simulated mutations left after simplification correspond to simulated nodes left after simplification (the maximum node_id in the mutation table is less than or equal to the number of nodes - 1). And that seems to be the case. So the results are consistent.  The only feature untouched by the simplification process is the SiteTable position, but I'm not sure how to relate the node_id it's associated with in the simulation with the node_id after simplification to check for correctness. 

- RE: recurrent mutation. Aye, I'll keep that in mind for larger simulations.

**Comment by molpopgen** [comment]
Cool--I'll take a look ASAP.  

I would wager that the simplification is working correctly, else msprime would throw an error.

One test is to simplify first down to the current generation, and see how many mutations there are.  I think you can also use the msprime API to map each mutation -> each tip that it'd be found in, and that data should match up to what was generated during the simulation.

Then, load the resulting tables and simplify down to a random sample.  The only mutations remaining should be the "right" subset from the mapping in the entire pop described above.

**Comment by DL42** [comment]
I'll try it out!

**Comment by jeromekelleher** [comment]
> The only feature untouched by the simplification process is the SiteTable position, but I'm not sure how to relate the node_id it's associated with in the simulation with the node_id after simplification to check for correctness. 

Just spotted this in my GitHub feed...

In case you want to check this, there is a ``map_nodes`` argument to ``TreeSequence.simplify`` which will return the mapping of node IDs in the input tree sequence to the output. See the [docs](
http://msprime.readthedocs.io/en/latest/api.html#msprime.TreeSequence.simplify). 

If you're using ``simplify_tables`` (as I guess you are), then you can pass a numpy array (dtype=int32) to simplify_tables which it will fill in, e.g.
```
node_map = np.empty(len(nodes), dtype=np.int32)
msprime.simplify_tables(nodes=nodes, edges=edges, node_map=node_map)
```
The ``node_map`` array will then contain the map of old node IDs to new node IDs.

**Comment by DL42** [comment]
I'll try it out, but I think that will indeed do the trick. Thanks Jerome!

**Pull request merged**
