### PR TITLE
Ancestral sample

### PR DESCRIPTION
**Pull request by DL42**
Minimal example for taking ancestral samples of a forward simulation. Currently has 277 lines of code, to fit into 60 lines of code, it still needs over 100 lines removed (the rest are comments).

### CODE REVIEW

**Comment by DL42** [comment]
A lot more cutting ... and it is down to 101 lines, 52 with the comments struck out. I made it!

This minimal example includes diploid bookkeeping, regular garbage collection, prior history, and ancestral samples.

**Comment by molpopgen** [comment]
@jeromekelleher @petrelharp @ashander

We've got a streamlined prototype of handling ancestral sampling and mutation.  Hopefully this is close to something that could go into the msprime docs.

**Comment by DL42** [comment]
Actually I cut handling mutation for space, but I have 7-8 lines to play with, I could add some sort of mutation handling back in. I might be able to make it poisson (as opposed to just adding 1 single mutation per node) in the space left, but I don't think I can also check to make sure each position added to the simulation is unique ... however, one could argue it is not necessary in this case (especially with no recombination) since each row in "site" is a unique identifier above and beyond position - unless msprime simplifies sites with the same position down to one site?

**Comment by molpopgen** [comment]
@DL42 My mistake!  I think that checking mutation position uniqueness is important for correctness.  I also think that it is useful to show how to do this in Python.

Any simplification that would be done on the sites is dependent on the properties of the RNG, meaning that any differences in simulation outcome vs. predictions from theory are off by something that's not a modeling decision.

**Comment by DL42** [comment]
> My mistake! I think that checking mutation position uniqueness is important for correctness. I also think that it is useful to show how to do this in Python.

Aye, fair enough.

> Any simplification that would be done on the sites is dependent on the properties of the RNG, meaning that any differences in simulation outcome vs. predictions from theory are off by something that's not a modeling decision.

I'm not quite sure I follow. In the case of recombination in the simulation (or even more generally with selection in simulation), I can see where things would go wrong, but in this instance I'm not sure if the actual mutation position matters. Theoretically I could put all mutations in the same genomic position and the number of mutations on each branch would be okay. However, I agree that this approach would be wrong in the general simulation case where mutation position matters and that we should endeavor to show correctness in examples whenever possible. But am I missing something where this simulation would also be wrong if we ignore mutation position?

**Comment by molpopgen** [comment]
> I'm not quite sure I follow. In the case of recombination in the simulation (or even more generally with selection in simulation), I can see where things would go wrong, but in this instance I'm not sure if the actual mutation position matters. Theoretically I could put all mutations in the same genomic position and the number of mutations on each branch would be okay. However, I agree that this approach would be wrong in the general simulation case where mutation position matters and that we should endeavor to show correctness in examples whenever possible. But am I missing something where this simulation would also be wrong if we ignore mutation position?

You mentioned that the site table may collapse things w/the same position--that should be a worry, right? If you generate the same mutation position more than once and you are not trying to do recurrent mutation, then you are doing so at the rate at which the RNG generates the same double 2x in the same interval (within a given period of time).  Then, if two sites simplify into one, haven't you implemented a bizarre form of back-mutation?

**Comment by DL42** [comment]
> You mentioned that the site table may collapse things w/the same position--that should be a worry, right? 

I wasn't sure if it does or not, but now that I think about it, I don't think it matters ... I could have 1 site in the site table and all the mutations listed at that site (a sort of infinite alleles model). The number of mutations should still hold. I can test this. 

> If you generate the same mutation position more than once and you are not trying to do recurrent mutation, then you are doing so at the rate at which the RNG generates the same double 2x in the same interval (within a given period of time). Then, if two sites simplify into one, haven't you implemented a bizarre form of back-mutation?

Except in this simulation, mutation position and in fact genome position overall is immaterial. There is only one interval 0-1. There isn't any recombination to break up mutations. I think how I'm thinking of this is more of an infinite allele model rather than a back-mutation scenario, but where, because position is irrelevant as there is no recombination, the predictions from the infinite allele/infinite sites model are basically identical.

**Comment by DL42** [comment]
After Skyping with Kevin, we've cleared up a bunch of stuff and there are three main options and a secondary option we could do regardless of the main option choice. it comes down to what Jerome would feel is most beneficial as an example for his documentation:

Option 1: Leave the program as a node & edge simulation ignoring mutation and recombination. The main purpose of this example is to show who to do node/edge bookkeeping with ancestral samples which also shows how to do diploid simulations and add prior history. This example would be 52 lines of code (without comments).

Option 2: Add modeling of infinite alleles (but still no recombination). In this case, every mutation would be added to the same site (so the site table would have 1 entry and every mutation would link to it ... or 1-1 sites-mutations but every site in the site table has the same position). This would be relatively simple; I could almost certainly get it under the 60 lines of code recommended; and the minimal example would now be able to have mutations on the ancestral tree - it would be more complete. 

Option 3: Add full modeling of infinite sites (but still no recombination). In this case, mutations would be added at unique position with a lookup done to ensure the uniqueness of each position. This would be the most reflective of a full forward simulation but the lookup would push us over the suggested 60 lines of code.

Option A: This is a secondary option. While option 1-3 are meant to show how to do it correctly, it might be nice to also contrast the chosen option with what happens if the ancestral sampling is not done correctly. In the case of option 1, we would add two examples (or one example with two versions) where we add mutations and print trees. For options 2 and 3, one would just create a false version with incorrect ancestral handling. These "bad" examples could be useful as the difference between right and wrong becomes very clear when you see the wrong tree printed and especially when there are mutations on that tree (or there "should" be and aren't - "should" in quotes because some of the long branches aren't real).

**Comment by DL42** [comment]
So I discovered a sorting problem in my ancestral sample prototypes. 

In order to solve the problem of ancestral samples needing to be in the back AND the ancestral samples not overlapping with the generational samples, I took the set of the combined ancestral and generational node ID lists and then reverse sorted the node IDs. However, this meant that the would-be parents were in the reverse order from where they were in fw simulation.

Unlike the previous bug, this doesn’t mean the simulation output was invalid. It’s actually still a valid simulation. However, it does mean that if the GC interval is changed, the results are inconsistent as different parents are chosen - some because they are now in reverse order, others because they are not in reverse order. 

So instead of:

all_samples = sorted(set(anc_samples.tolist() + samples.tolist()), reverse=True)

I now use this:

all_samples = samples.tolist() + [i for i in sorted(anc_samples.tolist()) if i not in samples.tolist()]

I have updated my code and pushed the changes to the pull request.

**Comment by molpopgen** [comment]
> all_samples = samples.tolist() + [i for i in sorted(anc_samples.tolist()) if i not in samples.tolist()]

Does this result in the same output for all GC intervals?  Confused as to if this is a potential solution to the problem?  What is the problem you are referring to?

**Comment by DL42** [comment]
Sorry for not being as clear as I'd hoped to be! It looks like from the email chain, that you figured it out. But for completeness sake of the record on here, yes that results in the same output for all GC intervals as it no longer changes the would-be parent node ID sorting.

**Pull request merged**
